### ISSUE TITLE
Cannot install circRNAprofiler on R version 4.2.2

### ISSUE THREAD

**Issue by simeix00** [Aufiero/circRNAprofiler#12]
I'm unable to install circRNAprofiler on the latest version of RStudio (last updated 31/10/22). This is the message I get when trying to install circRNAprofiler:
```
> install.packages("circRNAprofiler")
Warning in install.packages :
  unable to access index for repository https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/big-sur-arm64/contrib/4.2:
  cannot open URL 'https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://R-Forge.R-project.org/bin/macosx/big-sur-arm64/contrib/4.2:
  cannot open URL 'https://R-Forge.R-project.org/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://www.rforge.net/bin/macosx/big-sur-arm64/contrib/4.2:
  cannot open URL 'https://www.rforge.net/bin/macosx/big-sur-arm64/contrib/4.2/PACKAGES
```

This is what happens once I try to load the package:
```
> library(circRNAprofiler)
Error: package or namespace load failed for ‘circRNAprofiler’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/genefilter/libs/genefilter.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/genefilter/libs/genefilter.so, 0x0006): Library not loaded: '/opt/R/arm64/gfortran/lib/libgfortran.5.dylib'
  Referenced from: '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/genefilter/libs/genefilter.so'
  Reason: tried: '/opt/R/arm64/gfortran/lib/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file)
```

**Comment by simoauf** [comment]
Hi simeix00, I will check and let you know.

**Comment by simoauf** [comment]
Hi simeix, I just noticed that you used install.packages("circRNAprofiler"), you should not use install.packages but BiocManager::install("circRNAprofiler"). Have a look also here:
https://bioconductor.org/packages/release/bioc/html/circRNAprofiler.html

**Comment by simeix00** [comment]
> 

Hello simoauf, I tried both methods and I believe both did not work. Sorry for the confusion there.

**Comment by Aufiero** [comment]
For me, everything works fine. I also checked the Bioconductor and both the release (R version 4.2, Bioconductor version 3.16) and the development versions (R version 4.3, Bioconductor version 3.17) of circRNAprofiler were built correctly.   

Maybe something got corrupted during the installation, so you can try to delete the R folder (e.g. R-4.2.0) where the packages are installed, usually in  C:\Program Files\R, and then reinstall everything with BiocManager::install.
