### ISSUE TITLE
Error in `dplyr::bind_rows()`: Cannot Combine Different Data Types - Seeking Assistance from CircRNAprofiler Author

### ISSUE THREAD

**Issue by Li-Yaoting** [Aufiero/circRNAprofiler#13]
Hello, Authors of CircRNAprofiler. I'm encountering an error when using the module backSplicedJunctions <- getBackSplicedJunctions(gtf). The error message says " Error in `dplyr::bind_rows()`: ! Can't combine `..1$startUpBSE` <double> and `..2$startUpBSE` <character>.
Could you provide guidance on how to resolve this issue? I am using the following package versions: R (v 4.3.1), CircRNAprofiler (v 1.14), and dplyr (v 1.1.2). The data I am using is the output after annotation of circExplorer2 (v2.3.8), with the addition of a header before reading. The data format is shown in the image attached. Prior to analysis with CircRNAprofiler, I checked the project folder using checkProjectFolder, and the result was 0. Could you please advise on how to address this dplyr data merging error? Thank you.
<img width="1425" alt="data" src="https://github.com/Aufiero/circRNAprofiler/assets/54201517/12d6a9bf-a820-4b5a-890a-a714506ed1b8">

<img width="611" alt="error" src="https://github.com/Aufiero/circRNAprofiler/assets/54201517/f011385a-3dad-4bc8-86b5-7995ec2e4f56">

**Comment by Li-Yaoting** [comment]
environment and package version
<img width="1148" alt="version" src="https://github.com/Aufiero/circRNAprofiler/assets/54201517/88e64c32-6da9-4ff7-bca7-8124ba19da2c">

**Comment by Aufiero** [comment]
Sorry for the late reply. I´ll have a look and come back to you in the following days.

**Comment by Aufiero** [comment]
If you send me the file I will do a test and let you know.

**Comment by Li-Yaoting** [comment]
The following file is a test file that can be used, exported from the circExplorer2 software.
[SRR6890663_GSM3066231_G01S01Y_Young_1.known.txt](https://github.com/Aufiero/circRNAprofiler/files/13063362/SRR6890663_GSM3066231_G01S01Y_Young_1.known.txt)

**Comment by simoauf** [comment]
Thanks for providing the file, I'll do a test in the next days and I'll you know.

**Comment by Aufiero** [comment]
circRNAprofiler was tested with circExplorer2 v2.3.4 output file (circularRNA_full.txt). I tested with the latter file and it was working fine. The error arise when I used the file that you have provided. In any case I fixed the error dplyr::bind_rows(), so you should now be able to use it. Install the latest version ( Release 3.18) of circRNaprofiler.

**Comment by Aufiero** [comment]
Could you let me know if it works?

**Comment by Li-Yaoting** [comment]
Thanks,it work. However, if the first line of the circularRNA_full.txt file has "ciRNA" as circtype, an error will occur. I hope it can be fixed, corresponding to the circularRNA_full.txt file.
[SRR20204938_GSM6338657_29256.2.circularRNA_known.txt](https://github.com/Aufiero/circRNAprofiler/files/13402440/SRR20204938_GSM6338657_29256.2.circularRNA_known.txt)
![image](https://github.com/Aufiero/circRNAprofiler/assets/54201517/6272d8d8-8ad7-450a-a71a-e8fc55cff767)

**Comment by Aufiero** [comment]
Why do you have ciRNA rather than circRNA?

**Comment by Aufiero** [comment]
What you can do for now is to preprocess the file, by changing ciRNA with circRNA and it should work.
