### ISSUE TITLE
Use of two un-supported ‘other’ circRNA detection programs

### ISSUE THREAD

**Issue by mw-neuro** [Aufiero/circRNAprofiler#14]
It seems that the program allows for only one folder of ‘other’ circRNA input files…so I’m  wondering if there is a work around to merge BS junctions from multiple circRNA detection programs, of which, two are unsupported/‘other’ and don’t have there own inbuild import function? 

Thanks in advance!

**Comment by Aufiero** [comment]
I´ll have a look and come back to you in the following days.

**Comment by Aufiero** [comment]
The functionalities that you ask for can be implemented, and you will be able to use for now max 3 unsupported/‘other’. I will implement this in the next days. I'll let you know when it is done.

**Comment by Aufiero** [comment]
You can now use up to 3 unsupported tools, see vignette.  You have to install the latest devel version of circRNAprofiler.

**Comment by mw-neuro** [comment]
Thanks very much for adding this feature so quickly!!
