### ISSUE TITLE
(!): .txt file reported in experiment.txt is not present in folder

### ISSUE THREAD

**Issue by xiongxxp** [Aufiero/circRNAprofiler#3]
Hi Simona,
Nice circular RNA study tool. I tried the package today. When I enter the command "check <- checkProjectFolder()", there is an error. It says " .txt file reported in experiment.txt is not                       present in folder named circexplorer2". But I did put all cicRNAs__X.txt files in the folder. I don't know why the program still couldn't locate them. Please refer to the 
<img width="953" alt="circRNAprofiler" src="https://user-images.githubusercontent.com/52878331/85248911-18ad4200-b407-11ea-8869-c056ab9e2fb7.png">
screen shot. Thank you for your help.

**Comment by Aufiero** [comment]
Hi, thanks.
I'll check it out and let you know.
Can you also show me experiment.txt?

Simona

**Comment by xiongxxp** [comment]
Hi Simona,
Thank you for your prompt reply. Here is the screenshot for experiment.txt.
<img width="952" alt="experiment" src="https://user-images.githubusercontent.com/52878331/85259686-51a4e100-b41e-11ea-8992-c4231e9f2c7c.png">
I guess it's the directory problem. If I use setwd("d:/projectCirc") as directory. Then it shows ".txt file reported in experiment.txt is not present in folder named circexplorer2". But if I use setwd("d:/projectCirc/circexplorer2") as the directory, the error is missing gtf file & experiment.txt is absent or empty, and the program was able to locate those cicRNAs__X.txt files.
I assume d:/projectCirc is the main working directory. 
Thank you.

**Comment by Aufiero** [comment]
Hi, 
projectCirc needs to be set as your working directory. 
I think the problem is in experiment.txt, you missed the .txt in your file names, you only wrote circRNAs_0.37, it has to be circRNAs_0.37.txt, circRNAs_0.38.txt etc

Let me know when you correct if it works.

S

**Comment by xiongxxp** [comment]
Hi Simona,
Yes, you are right. I missed .txt in the experiment.txt. file. Now it works.
Besides, do I still need to run mergeBSJunctions() command since I have only one circRNA detection tool (circexplorer2). And the manual is for multiple detection tools. How do I modify accordingly based on only 1 tool (not sure about the step of mergeBSJunctions() and filterCirc())? Thank you.
Best,
XP

**Comment by Aufiero** [comment]
Hi, 

You can run mergeBSJunctions() also if you used only 1 circRNA detection tool, or in this case you can also skip this step and use directly the backSplicedJunctions dataframe generated by getBackSplicedJunctions() for the downstream steps, e.g.:

`filteredCirc <- filterCirc(backSplicedJunctions, allSamples = FALSE, min = 5). `

I'll will specify that in the vignettes so that it is clearer.

Best,
S
