### ISSUE TITLE
how  to get expression of circRNA from clean.result (NCLscan)

### ISSUE THREAD

**Issue by JianGuoZhou3** [Aufiero/circRNAprofiler#6]
I used NCLscan
````
 ./NCLscan.py -c ./NCLscan.config -pj clean -o output --fq1 simu_5X_100PE_1.fastq --fq2 simu_5X_100PE_2.fastq
````

After run,

````
 cd output
(base) [rstudio@Zhou-EU-2 output]$ ls
all.clean.1.result          clean.3b.info          clean.JS2.Idx           clean.chi.bed                   clean.main.bwa.unmapped_1.fastq  clean.preJS.seq2
all.clean.1.sam             clean.4.info           clean.JS2.cleaned.info  clean.chi0.bed                  clean.main.bwa.unmapped_2.fastq  clean.preResult
all.clean.1b.result         clean.4b.info          clean.JS2.fa            clean.chi2.bed                  clean.main.sam                   clean.rG.non_un.psl
all.clean.1b.sam            clean.JS.GRCh37.2.psl  clean.JS2.info          clean.chi3.bed                  clean.main.um3.fa                clean.rG.psl
all.clean.JS.Parsered.sam   clean.JS.GRCh37.psl    clean.JS2.info_1        clean.chrM.2.psl                clean.main.unmapped.fa           clean.rG.um3.psl
all.clean.JS.sam            clean.JS.cleaned.info  clean.JS2.info_2        clean.chrM.um3.psl              clean.main.unmapped.sam          clean.result
all.clean.JS2.sam           clean.JS.clear.fa      clean.JS2.ndx           clean.coding.2.psl              clean.main.unmapped.sam.id       clean.result.info
all.clean.JS2b.sam          clean.JS.fa            clean.JS2.preIdx        clean.coding.um3.psl            clean.main.unmapped_1.fastq      clean.result.sam
all.clean.b.result          clean.JS.info          clean.JS2.prefa         clean.colinear.psl              clean.main.unmapped_2.fastq      clean.result.tmp
all.clean.result            clean.JS.info_1        clean.JS2.result.info   clean.info                      clean.main_1.JS.sam              clean.result.tmp2
all.clean.um3.colinear.psl  clean.JS.info_2        clean.JS2.seq           clean.linearJS                  clean.main_1.um3.fastq           clean.result.tmp3
all.clean.um3.fa            clean.JS.ndx           clean.JS2.seq_1         clean.lncRNA.2.psl              clean.main_2.JS.sam              clean.tmp.info
clean.2.chi.bed             clean.JS.seq           clean.JS2.seq_2         clean.lncRNA.um3.psl            clean.main_2.um3.fastq           clean.tmp2.info
clean.2.info                clean.JS.seq12         clean.PreJS2.bed        clean.main.JS2.sam              clean.ncl.sam                    clean.un.psl
clean.2.info.GRCh37.psl     clean.JS.seq_1         clean.PreJS2.info       clean.main.JS2b.sam             clean.preJS.bed                  clean.unmapped.2.fa
clean.2.info.fa             clean.JS.seq_2         clean.PreJS2.info2      clean.main.bwa.bam              clean.preJS.info                 clean.unmapped.fa
clean.2b.info               clean.JS1.Idx          clean.PreJS2.seq        clean.main.bwa.unmapped.sam     clean.preJS.info2                temp.list
clean.3.info                clean.JS1.preIdx       clean.PreJS2.seq2       clean.main.bwa.unmapped.sam.id  clean.preJS.seq                  tmp.info
```
But, I don't know keep which docunments and input to circRNAprofiler.
Best,

**Comment by Aufiero** [comment]
Hi,

the file to use should be a file ending with .result so in your case should be clean.result
See the package vignettes to see how to run circRNAprofiler and get expression from this file. 

Best,
S

**Comment by JianGuoZhou3** [comment]
Hi,
so, I can remove others?
I will try and feedback to you.
Best,

**Comment by Aufiero** [comment]
I do not get your question.
If you used only NCLscan you should have in your project folder named e.g. projectCirc only 1 subfolder named nclscan. Please follow the vignettes instructions.  For example purpose a project folder named projectCirc was created in inst/extdata folder of the R package circRNAprofiler. You can have a look at it and modify that accordingly. 

Best,
S

**Comment by JianGuoZhou3** [comment]
for sure, I got it.
But now still have some errors.
I test nclscan and circexplorer2 independently.
![image](https://user-images.githubusercontent.com/20199977/90129691-61c7a580-dd69-11ea-8a81-7e74ee055822.png)
![image](https://user-images.githubusercontent.com/20199977/90129789-920f4400-dd69-11ea-9095-9b8cdde08cd1.png)
however, there are errors.

````
# gtf <- formatGTF("gencode.V19.annotation.gtf")
gtf <- formatGTF("gencode.v34.annotation.gtf")
# For example purpose load a short version of the formatted gtf file generated
# using the command above.
data("gtf")
head(gtf)
save(gtf,file = "gencode.v34.hg38.gtf.Rdata")

````
````
> backSplicedJunctions <- getBackSplicedJunctions(gtf)
Error: Can't combine `..1$id` <logical> and `..2$id` <character>.
Run `rlang::last_error()` to see where the error occurred.
````
There are my documents.
Could you please help me to check those?
Best,
[circexplorer2.zip](https://github.com/Aufiero/circRNAprofiler/files/5068746/circexplorer2.zip)
[nclscan.zip](https://github.com/Aufiero/circRNAprofiler/files/5068750/nclscan.zip)
[experiment.txt](https://github.com/Aufiero/circRNAprofiler/files/5068751/experiment.txt)

[gencode.v34.hg38.gtf.Rdata.zip](https://github.com/Aufiero/circRNAprofiler/files/5068759/gencode.v34.hg38.gtf.Rdata.zip)

**Comment by Aufiero** [comment]
Can you run sessionInfo() and send it to me? I want to see first if there is a problem with package versions.

**Comment by JianGuoZhou3** [comment]
````
> sessionInfo()
````
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] gridExtra_2.3                          
 [2] VennDiagram_1.6.20                     
 [3] futile.logger_1.4.3                    
 [4] ggpubr_0.4.0                           
 [5] ggplot2_3.3.2                          
 [6] circRNAprofiler_1.0.0                  
 [7] gwascat_2.18.0                         
 [8] Homo.sapiens_1.3.1                     
 [9] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
[10] org.Hs.eg.db_3.10.0                    
[11] GO.db_3.10.0                           
[12] OrganismDbi_1.28.0                     
[13] GenomicFeatures_1.38.2                 
[14] GenomicRanges_1.38.0                   
[15] GenomeInfoDb_1.22.1                    
[16] AnnotationDbi_1.48.0                   
[17] IRanges_2.20.2                         
[18] S4Vectors_0.24.4                       
[19] Biobase_2.46.0                         
[20] BiocGenerics_0.32.0                    

loaded via a namespace (and not attached):
  [1] readxl_1.3.1                      backports_1.1.8                  
  [3] Hmisc_4.4-1                       AnnotationHub_2.18.0             
  [5] BiocFileCache_1.10.2              plyr_1.8.6                       
  [7] splines_3.6.3                     BiocParallel_1.20.1              
  [9] digest_0.6.25                     htmltools_0.5.0                  
 [11] magrittr_1.5                      checkmate_2.0.0                  
 [13] memoise_1.1.0                     BSgenome_1.54.0                  
 [15] cluster_2.1.0                     openxlsx_4.1.5                   
 [17] limma_3.42.2                      Biostrings_2.54.0                
 [19] readr_1.3.1                       annotate_1.64.0                  
 [21] matrixStats_0.56.0                R.utils_2.9.2                    
 [23] askpass_1.1                       prettyunits_1.1.1                
 [25] jpeg_0.1-8.1                      colorspace_1.4-1                 
 [27] blob_1.2.1                        rappdirs_0.3.1                   
 [29] haven_2.3.1                       xfun_0.16                        
 [31] dplyr_1.0.1                       crayon_1.3.4                     
 [33] RCurl_1.98-1.2                    graph_1.64.0                     
 [35] genefilter_1.68.0                 survival_3.2-3                   
 [37] glue_1.4.1                        gtable_0.3.0                     
 [39] zlibbioc_1.32.0                   XVector_0.26.0                   
 [41] seqinr_3.6-1                      DelayedArray_0.12.3              
 [43] car_3.0-9                         abind_1.4-5                      
 [45] scales_1.1.1                      futile.options_1.0.1             
 [47] DBI_1.1.0                         edgeR_3.28.1                     
 [49] rstatix_0.6.0                     Rcpp_1.0.5                       
 [51] xtable_1.8-4                      progress_1.2.2                   
 [53] htmlTable_2.0.1                   foreign_0.8-75                   
 [55] bit_4.0.4                         Formula_1.2-3                    
 [57] htmlwidgets_1.5.1                 httr_1.4.2                       
 [59] RColorBrewer_1.1-2                ellipsis_0.3.1                   
 [61] pkgconfig_2.0.3                   XML_3.99-0.3                     
 [63] R.methodsS3_1.8.0                 nnet_7.3-14                      
 [65] dbplyr_1.4.4                      locfit_1.5-9.4                   
 [67] tidyselect_1.1.0                  rlang_0.4.7                      
 [69] reshape2_1.4.4                    later_1.1.0.1                    
 [71] cellranger_1.1.0                  munsell_0.5.0                    
 [73] BiocVersion_3.10.1                tools_3.6.3                      
 [75] generics_0.0.2                    RSQLite_2.2.0                    
 [77] ade4_1.7-15                       broom_0.7.0                      
 [79] stringr_1.4.0                     fastmap_1.0.1                    
 [81] yaml_2.2.1                        knitr_1.29                       
 [83] bit64_4.0.2                       zip_2.1.0                        
 [85] purrr_0.3.4                       RBGL_1.62.1                      
 [87] mime_0.9                          formatR_1.7                      
 [89] R.oo_1.23.0                       biomaRt_2.42.1                   
 [91] compiler_3.6.3                    rstudioapi_0.11                  
 [93] curl_4.3                          png_0.1-7                        
 [95] interactiveDisplayBase_1.24.0     ggsignif_0.6.0                   
 [97] tibble_3.0.3                      geneplotter_1.64.0               
 [99] stringi_1.4.6                     forcats_0.5.0                    
[101] lattice_0.20-41                   Matrix_1.2-18                    
[103] vctrs_0.3.2                       pillar_1.4.6                     
[105] lifecycle_0.2.0                   BiocManager_1.30.10              
[107] data.table_1.12.8                 bitops_1.0-6                     
[109] httpuv_1.5.4                      rtracklayer_1.46.0               
[111] R6_2.4.1                          latticeExtra_0.6-29              
[113] promises_1.1.1                    rio_0.5.16                       
[115] lambda.r_1.2.4                    MASS_7.3-51.6                    
[117] assertthat_0.2.1                  SummarizedExperiment_1.16.1      
[119] openssl_1.4.2                     DESeq2_1.26.0                    
[121] withr_2.2.0                       GenomicAlignments_1.22.1         
[123] Rsamtools_2.2.3                   GenomeInfoDbData_1.2.2           
[125] hms_0.5.3                         rpart_4.1-15                     
[127] tidyr_1.1.1                       carData_3.0-4                    
[129] BSgenome.Hsapiens.UCSC.hg19_1.4.0 shiny_1.5.0                      
[131] base64enc_0.1-3

**Comment by Aufiero** [comment]
I see that you are the wrong version of circRNAprofiler. 
I suggest that you alway use BiocManager to install packages since it takes care of installing the package of interest and the correct versions of all the dependencies. 

On the github page it is specified how to install circRNAprofiler. 

**Run 1) or 2).** 

**1) You can install the release version (STABLE and recommended) of circRNAprofiler from Bioconductor using:**
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("circRNAprofiler")
To download the latest development version on github use:
```
**2) OR you can install the devel version (with some improvements) of circRNAprofiler from Bioconductor using:**
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("circRNAprofiler")
```

Once you have done that you should not get any error. 

Best,
S

**Comment by JianGuoZhou3** [comment]
Hi, there are some errors.
````
library(circRNAprofiler)
Error: package or namespace load failed for ‘circRNAprofiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘ape’
````

````
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
````

````
> install.packages("ape")

  There is a binary version available but the source version
  is later:
    binary source needs_compilation
ape    5.4  5.4-1              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) y
installing the source package ‘ape’

trying URL 'https://cran.rstudio.com/src/contrib/ape_5.4-1.tar.gz'
Content type 'application/x-gzip' length 798605 bytes (779 KB)
==================================================
downloaded 779 KB

* installing *source* package ‘ape’ ...
** package ‘ape’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c BIONJ.c -o BIONJ.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c NNI.c -o NNI.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c SPR.c -o SPR.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c additive.c -o additive.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ape.c -o ape.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c bNNI.c -o bNNI.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c bionjs.c -o bionjs.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c bipartition.c -o bipartition.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c bitsplits.c -o bitsplits.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c delta_plot.c -o delta_plot.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c dist_dna.c -o dist_dna.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c dist_nodes.c -o dist_nodes.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ewLasso.c -o ewLasso.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c heap.c -o heap.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c mat_expo.c -o mat_expo.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c me.c -o me.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c me_balanced.c -o me_balanced.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c me_ols.c -o me_ols.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c mvr.c -o mvr.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c mvrs.c -o mvrs.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c nj.c -o nj.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c njs.c -o njs.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c pic.c -o pic.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c plot_phylo.c -o plot_phylo.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c prop_part.cpp -o prop_part.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rTrait.c -o rTrait.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c read_dna.c -o read_dna.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c reorder_Rcpp.cpp -o reorder_Rcpp.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c reorder_phylo.c -o reorder_phylo.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c treePop.c -o treePop.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c tree_build.c -o tree_build.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c tree_phylo.c -o tree_phylo.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c triangMtd.c -o triangMtd.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c triangMtds.c -o triangMtds.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ultrametric.c -o ultrametric.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o ape.so BIONJ.o NNI.o RcppExports.o SPR.o additive.o ape.o bNNI.o bionjs.o bipartition.o bitsplits.o delta_plot.o dist_dna.o dist_nodes.o ewLasso.o heap.o mat_expo.o me.o me_balanced.o me_ols.o mvr.o mvrs.o nj.o njs.o pic.o plot_phylo.o prop_part.o rTrait.o read_dna.o reorder_Rcpp.o reorder_phylo.o treePop.o tree_build.o tree_phylo.o triangMtd.o triangMtds.o ultrametric.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ape.so] Error 1
ERROR: compilation failed for package ‘ape’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ape’
Warning in install.packages :
  installation of package ‘ape’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/h1/wph5l7kn6sq020007z1bq2d00000gn/T/RtmpSZFWW3/downloaded_packages’

````

Do you have any method to solve this?
Best,

**Comment by Aufiero** [comment]
Hi,

I can not reproduce the error. 

-Try to close everything, R or R studio, and install the ape package using BiocManager. 

-An alternative you can reset everything so this means that you can delete all the packages in the user R library folder 4.0  that usually is e.g. your user/R/win-library and run again: 
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("circRNAprofiler")
```

This command should install all the required packages. 

After you have done that can you run sessionInfo() and post it here? 

Best,
S

**Comment by JianGuoZhou3** [comment]
Hi Thanks,
After deleting all of R and related documents, and re-install this package.
Now, it works, and very convenient.
Best,
